### ISSUE TITLE
Event says it can start but it can't

### ISSUE THREAD

**Issue by sbash** [BattleDrome/Core#7]
The event says it can start, but then kicks up an error:

![image](https://user-images.githubusercontent.com/18412275/38005322-3bd08030-320e-11e8-955f-883b84f89100.png)

**Comment by pmumby** [comment]
This one is a duplicate (or an extension) of the Event UI needing a re-work.

This isn't actually a bug, just poorly designed UI.

The Event says "Can Start Now" which usually means there is a mandatory waiting period once an event is created, during which you can join, but the event can't start (even if there is enough people, etc). In this case the reason for the error is because the minimum number of warriors has not been met (which is shown, but it's unclear).

This UI needs a complete re-work. I'll merge this with the other Event UI issue.

Thanks!

**Comment by pmumby** [comment]
Related to #1 Closing this issue, and referencing there.
