### ISSUE TITLE
Alerts are over top the create button

### ISSUE THREAD

**Issue by sbash** [BattleDrome/Core#8]
![image](https://user-images.githubusercontent.com/18412275/38005415-8381f058-320e-11e8-9c3e-c4cb4113a366.png)

**Comment by sbash** [comment]
Also covers up the cards after 2 warriors!

**Comment by pmumby** [comment]
This is unfortunately the nature of hovering notifications like this. No matter where you put them they cover some UI elements.

Ideally we'd have a full notification tray with a badge calling out the notification count.

Will have to be done in a future UI re-work. 

For now moving to a "New Warrior" card instead of a button might be a better interim approach. Will investigate if this can be done as a short-term fix, and plan on a bigger re-work of the notification UI in the beta.
